In [2]:
import numpy as np
from scipy.spatial.transform import Rotation as R

In [ ]:
# 0.707107i + 0.707107j + 4.32978e-17k + 4.32978e-17

In [7]:

# NED_ENU_Q : 0.707107i + 0.707107j + 4.32978e-17k + 4.32978e-17
# AIRCRAFT_BASELINK_Q : 1i + 0j + 0k + 6.12323e-17
# (NED_ENU_Q * quat_in) = 1.13137i + -0.141421j + -0.00700036k + -0.00714178
def rotate_quaternion_fromTo_ENU_NED(quat_in):
    # Static quaternion needed for rotating between ENU and NED frames
    euler_1 = np.array([np.pi, 0.0, np.pi/2])  # Roll, Pitch, Yaw in radians
    NED_ENU_Q = R.from_euler('xyz', euler_1).as_quat()  # Convert to quaternion [x, y, z, w]
    
    # Static quaternion needed for rotating between aircraft and base_link frames
    euler_2 = np.array([np.pi, 0.0, 0.0])  # Roll, Pitch, Yaw in radians
    AIRCRAFT_BASELINK_Q = R.from_euler('xyz', euler_2).as_quat()  # Convert to quaternion [x, y, z, w]

    # Convert input quaternion to scipy Rotation
    quat_in = np.roll(quat_in, -1)
    quat_in_rot = R.from_quat(quat_in)  # Input quaternion as [x, y, z, w]

    # Apply the rotations
    ned_enu_rot = R.from_quat(NED_ENU_Q)
    aircraft_baselink_rot = R.from_quat(AIRCRAFT_BASELINK_Q)

    # Final quaternion
    rotated_quat = ((ned_enu_rot * quat_in_rot) * aircraft_baselink_rot).as_quat()
    
    print(rotated_quat)

quat_in = np.array([ 2.33298051e-04 ,-5.32466883e-05, -1.24223489e-08,  9.99999971e-01])
quat_in = np.roll(quat_in, 1)
# a = rotate_quaternion_fromTo_ENU_NED(quat_in)
rotate_quaternion_fromTo_ENU_NED(quat_in)

[-1.27315540e-04 -2.02617728e-04 -7.07106770e-01 -7.07106752e-01]


In [ ]:
# import numpy as np
# from scipy.spatial.transform import Rotation as R

# def rotate_quaternion_from_to_enu_ned(quat_in):
#     """
#     Rotate a quaternion from ENU to NED frame and adjust for aircraft-baselink transformation.
    
#     Parameters:
#         quat_in (np.ndarray): Input quaternion in the format [w, x, y, z].
        
#     Returns:
#         np.ndarray: Rotated quaternion in the format [w, x, y, z].
#     """
#     # Static quaternion needed for rotating between ENU and NED frames
#     euler_1 = np.array([np.pi, 0.0, np.pi / 2])  # [roll, pitch, yaw] in radians
#     ned_enu_q = R.from_euler('zyx', euler_1).as_quat()  # Converts to [x, y, z, w]

#     # Static quaternion needed for rotating between aircraft and base_link frames
#     euler_2 = np.array([np.pi, 0.0, 0.0])  # [roll, pitch, yaw] in radians
#     aircraft_baselink_q = R.from_euler('zyx', euler_2).as_quat()  # Converts to [x, y, z, w]

#     # Convert input quaternion to scipy Rotation object
#     quat_in_rot = R.from_quat(quat_in)  # scipy expects [x, y, z, w]

#     # Apply rotations
#     ned_enu_rot = R.from_quat(ned_enu_q)
#     aircraft_baselink_rot = R.from_quat(aircraft_baselink_q)
#     result_rot = ned_enu_rot * quat_in_rot

#     # Convert result to [w, x, y, z] format
#     result_quat = result_rot.as_quat()  # [x, y, z, w]
#     return np.array([result_quat[3], result_quat[0], result_quat[1], result_quat[2]])
# # (NED_ENU_Q * quat_in) = 1.13137i + -0.141421j + -0.00700036k + -0.00714178
# rotate_quaternion_from_to_enu_ned(np.array([0.7, 0.01, 0.0001, 0.9]))


array([ 0.00613948, -0.00626351, -0.12402996,  0.99223971])

In [100]:
# importing numpy as geek 
import numpy as geek
 
arr = geek.array([[5, 6, 7, 8]])
 
gfg = arr.flatten('F')
 
print( gfg )

[5 6 7 8]


In [77]:
import numpy as np
from scipy.spatial.transform import Rotation as R

def rotate_quaternion_FromTo_ENU_NED(quat_in):
    """
    Rotate a quaternion between ENU and NED frames and also between aircraft and base_link frames.

    Parameters:
        quat_in: Input quaternion as a numpy array [x, y, z, w]

    Returns:
        Rotated quaternion as a numpy array [x, y, z, w]
    """
    # Static quaternion needed for rotating between ENU and NED frames
    euler_1 = np.array([np.pi, 0.0, np.pi/2])  # Roll, Pitch, Yaw in radians
    NED_ENU_Q = R.from_euler('zyx', euler_1[::-1]).as_quat()  # Convert to quaternion [x, y, z, w]

    # Static quaternion needed for rotating between aircraft and base_link frames
    euler_2 = np.array([np.pi, 0.0, 0.0])  # Roll, Pitch, Yaw in radians
    AIRCRAFT_BASELINK_Q = R.from_euler('zyx', euler_2[::-1]).as_quat()  # Convert to quaternion [x, y, z, w]

    # Convert input quaternion to scipy Rotation
    quat_in_rot = R.from_quat(quat_in)  # Input quaternion as [x, y, z, w]

    # Apply the rotations
    ned_enu_rot = R.from_quat(NED_ENU_Q)
    aircraft_baselink_rot = R.from_quat(AIRCRAFT_BASELINK_Q)

    # Final quaternion
    rotated_quat = (ned_enu_rot * quat_in_rot * aircraft_baselink_rot).as_quat()

    return rotated_quat

# Example usage:
quat_in = np.array([0.0, 0.0, 0.0, 1.0])  # Example input quaternion [x, y, z, w]
result = rotate_quaternion_FromTo_ENU_NED(quat_in)
arr = np.array([1,2,3,4])
print("Rotated quaternion:", result-arr)


Rotated quaternion: [-1.         -2.         -2.29289322 -4.70710678]


In [13]:
k_deg_to_rad = np.pi / 180.0
kS = np.sin(k_deg_to_rad * 45)
print(kS)
rotor_velocities_to_torques_and_thrust = np.array([[-kS, kS, kS, -kS],[-kS, kS, -kS, kS],[-1, -1, 1, 1],[1, 1, 1, 1]])

np.zeros((4,4))
print("hi", np.zeros((4,4)))


0.7071067811865475
hi [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np
position_W_ = np.zeros(3)
velocity_W_ = np.zeros(3)

r_position_W_ = np.zeros(3)
r_velocity_W_ = np.zeros(3)
r_acceleration_W_ = np.zeros(3)

position_gain_ = np.zeros(3)
velocity_gain_ = np.zeros(3)
attitude_gain_ = np.zeros(3)
angular_rate_gain_ = np.zeros(3)

_inertia_matrix = np.zeros(3)

angular_velocity_B_ = np.zeros(3)

R_B_W_ = np.zeros((3,3))

r_yaw = 0.0
r_yaw_rate = 0.0

_uav_mass = 1.0
_gravity = 9.8


e_p = position_W_ - r_position_W_
# 	1.2 The tracking errors for the velocity
# 	velocity_W_: vận tốc thực tế, r_velocity_W_ : vận tốc mong muốn
e_v = velocity_W_ - r_velocity_W_

# 2. caculate Iad: gia tốc mong muốn
unit_z = np.array([0, 0, 1])
I_a_d = (_uav_mass * _gravity * unit_z 
        - np.multiply(position_gain_, e_p) 
        - np.multiply(velocity_gain_, e_v)
        + _uav_mass * r_acceleration_W_)

# 3. lực đẩy T
thrust = I_a_d @ R_B_W_[:, 2]

# 4. Bzd
B_z_d = I_a_d / np.linalg.norm(I_a_d)

# 5. Calculate Desired Rotational Matrix
#  5.1 Bxd (do Bdx và Bdz ta cần chọn cho hai thằng này không song song)
B_x_d = np.array([np.cos(r_yaw), np.sin(r_yaw), 0.0])
#  5.1 Byd (từ Bzd and Bxd)
B_y_d = np.cross(B_z_d, B_x_d)  # Compute the cross product of B_z_d and B_x_d
B_y_d = B_y_d / np.linalg.norm(B_y_d)  # Normalize B_y_d



#  5.2 Rdw
# Assuming B_y_d and B_z_d are already defined
R_d_w = np.zeros((3, 3))  # Initialize a 3x3 matrix

# Fill columns of R_d_w
R_d_w[:, 0] = np.cross(B_y_d, B_z_d)  # First column
R_d_w[:, 1] = B_y_d                  # Second column
R_d_w[:, 2] = B_z_d                  # Third column

desired_quaternion = R.from_matrix(R_d_w).as_quat()

# 	6. the attitude tracking error eR
e_R_matrix = 0.5 * (R_d_w.T @ R_B_W_ - R_B_W_.T @ R_d_w)

e_R = np.array([ e_R_matrix[2, 1], e_R_matrix[0, 2], e_R_matrix[1, 0]])


# 	7.  the tracking error for the angular velocity e_omega
omega_ref = r_yaw_rate * unit_z
e_omega = angular_velocity_B_ - R_B_W_.T @ R_d_w @ omega_ref

# 8. Moment T (Attitude tracking)
tau = (
- np.multiply(attitude_gain_, e_R)  # Element-wise product
- np.multiply(angular_rate_gain_, e_omega)  # Element-wise product
+ np.cross(angular_velocity_B_, _inertia_matrix * angular_velocity_B_)
)
# Output the wrench
controller_torque_thrust = np.hstack((tau, thrust))

[0. 0. 0.]
0.0
[0. 0. 0. 0.]
